### ISSUE TITLE
Extension crashing - no usable version of libssl was found

### ISSUE THREAD

**Issue by kosude** [rstm-sf/view-avalonia-preview-vscode#14]
When using the extension on a machine running Arch Linux, the following messages are shown in the output tab:

```
No usable version of libssl was found
[Info  - 17:51:55] Connection to server got closed. Server will restart.
```

This repeats 5 times until `The server will not be restarted` shows up (referring to the 'Avalonia Preview Language Server') and the extension fails.

I have OpenSSL installed to the latest version:

```
$ openssl version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
```

**Comment by rstm-sf** [comment]
Hello,

try this option https://github.com/rstm-sf/view-avalonia-preview-vscode/actions/runs/4525983634

I upgraded .net version from 3.1 to 6. The problem seems to be gone https://github.com/rstm-sf/view-avalonia-preview-vscode/pull/15

https://github.com/dotnet/core/issues/4749#issuecomment-1332624412

**Comment by kosude** [comment]
I can confirm the crashes no longer occur on my end either. Thanks for the quick response!
